
from db.database import Base
from sqlalchemy import Column, Integer, String,Boolean,Float,DateTime

class trade_setting(Base):
    __tablename__ = 'trade_setting'
    row_id = Column(Integer(), primary_key=True, autoincrement=True)
    timezone = Column(String())
    lot_size = Column(Float())
    min_tick = Column(Float())
    random_id = Column(String())
    symbol = Column(String())
    order_type = Column(String())
    local_symbol = Column(String())
    inst_type = Column(String())
    account = Column(String())
    quantity = Column(Integer())
    percentage = Column(String())
    limit_offset = Column(Float())
    stop_offset = Column(Float())
    stop_loss = Column(Float())
    take_profit = Column(Float())
    moc_order = Column(Boolean())
    position_trade = Column(Boolean())
    reverse_trade = Column(Boolean())
    exitTime = Column(Integer())
    sttpexitTime = Column(Integer())
    trailing_stop = Column(Boolean())
    trailing_stop_percentage = Column(Float())
    stop_loss_percentage = Column(Boolean())
    take_profit_percentage = Column(Boolean())
    EntryOffsetInPercentage = Column(Boolean())
    TWSHost = Column(String())
    TWSPort = Column(String())
    TWSClientId = Column(String())
    Exchange = Column(String())
    TimeInForce = Column(String())
    MaturityDate = Column(String())
    MappedToSymbol = Column(String())
    Currency = Column(String())
    # Email Config
    symbolIndex = Column(Integer())
    sideIndex = Column(Integer())
    priceIndex = Column(Integer())
    emailSubject = Column(String())
    splitSymbol = Column(String())
    takeProfit = Column(Integer())
    stopLoss = Column(Integer())
    mailServer = Column(String())
    mailUsername = Column(String())
    mailPassword = Column(String())
    trustedEmail = Column(String())
    lastSwingTrade = Column(String())
    filterText = Column(String())
    fromDatetime = Column(String())
    toDatetime = Column(String())
    date_validation = Column(Boolean())
    # Telegram Config
    telegram_api_id = Column(Integer())
    telegram_api_hash = Column(String())
    discord_token = Column(String())
    TD_ameritrade_code = Column(String())
    TD_ameritrade_token = Column(String())
    TD_ameritrade_token_expiry = Column(DateTime())
    TD_ameritrade_refresh_token = Column(String())
    TD_ameritrade_refresh_token_expiry = Column(DateTime())
    TD_ameritrade_client_id = Column(String())
    TD_ameritrade_redirect_url = Column(String())
    TD_ameritrade_account = Column(String())
    eEntryOffset = Column(Float())
    duplicate_position = Column(Boolean())
    maximumOrder = Column(Integer())
    rth = Column(Boolean())
    manualchange = Column(Boolean())
    local_symbol_exp = Column(DateTime())


